---
title: Mooring Response to Unidirectional Flow
author: Dan Kelley
date: "`r Sys.Date()`"
bibliography: model.bib
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    fig_caption: yes
    fig_width: 3.5
    fig_height: 3.5
    dpi: 72
    dev.args: list(pointsize=11)
vignette: >
  %\VignetteIndexEntry{Mooring Response to Unidirectional Flow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  markdown:
    wrap: 72
---
\newcommand{\D}{{\cal D}}
\newcommand{\B}{{\cal B}}
\newcommand{\T}{{\cal T}}
\newcommand{\Eq}{Equation}

# Introduction

Anchored oceanographic mooring lines are deformed by currents, in much the same
way as trees are bent by wind.  For very simple moorings, e.g. consisting of a
single float connected by a uniform cable to an anchor at the bottom, the
deformation can be calculated if the current is uniform.  The physics is
analogous to the sagging of telephone lines between poles, and falls into the
general category of a catenary.  However, things are more complicated for
depth-varying currents, and for mooring lines that consist of many elements
connected by cables.

An approach to analysing realistic oceanographic moorings is to use lumped-mass
theory, in which elements such as floats and instrument packages are
parameterized by their buoyancy and drag characteristics, and in which cables
envisioned as connected line elements.  This approach was taken by
@dewey_mooring_1999 in a GUI-based Matlab system.  The present treatment is of
similar foundation, although with some added simplifications (such as
unidirectional current) that are relevant to the basic problem of computing
"knock-down", i.e. the vertical displacement of instruments that is caused
by slanting of the mooring line.

# Model

Consider the case of unidirectional horizontal current aligned with the $x$
axis. Following oceanographic convention, let $z$ be the vertical coordinate,
positive upwards, with $z=0$ at the surface.  The mooring is modelled as a
series of $n$ connected elements, with the top element being numbered $i$.
Water density and velocity are assumed to be a functions of depth, with values
$\rho_i$ and $u_i$ at the location $z_i$ of the $i$-th element.

Each element is described by the following properties.

* Length, $L_i$ [m].  For a portion of cable, this has the common meaning.  For
  a float, instrument, or other thing, it is the contribution that the item
  makes to the overall mooring length.
* Area, $A_i$ [m$^2$] projected in the $x$ direction.
* A measure of buoyancy force divided by $g$, the acceleration due to gravity.
  For a solid object, this is a simple number, expressed in kg, and denoted
  $m_i$ below. For a cable, it is expressed per unit length of cable, i.e. in
  kg/m, and denoted $\mu_i$ below.  Manufacturers tend to provide $m$ or $\mu$
  values in technical documentation about mooring components. Note that they
  refer to in-water buoyancy force, but the distinction between freshwater
  and seawater is seldom made clear.
* Drag coefficient, $C_i$, defined as the ratio of drag force, $\D_i$, to
  $\frac{1}{2}A_i\rho_i u_i|u_i|$.

A tension force exists between each interior mooring element.  The tension
above the $i$-th interior element (thus pulling upward on it) is denoted
$\T_i$, and $\T_{i+1}$ represents the tension pulling down from below.  These
tensions will be directed vertically if there is no current, but they will have
horizontal components with a current, because it will distort the mooring from
its upright orientation.  The angle made by the $i$-th element to the vertical
is represented with $\phi_i$.  Determining these two quantities, $\T$ and
$\phi$, is the key to inferring the response of a mooring to currents.

Quasi-steady dynamics are assumed, so that forces must balance in both the
horizontal and vertical directions. The tension force has components in both
the $x$ and $z$ directions, but the buoyancy force (defined as positive for
objects that would rise if unattached to a mooring) acts only in the vertical,
upwards if $m$ or $\mu$ is positive.

The buoyancy force for a solid object such as an anchor or a float is found
with (Equation 1)
\begin{equation}
\B_i = -g m_i
\end{equation}
while it is represented with (Equation 2)
\begin{equation}
\B_i = -g \mu_i \Delta l
\end{equation}
for a portion of a cable of length $\Delta l$.

The drag force is expressed with (Equation 3)
\begin{equation}
\D_i = \frac{1}{2} A_i C_i \rho_i u_i |u_i|
\end{equation}
where $A_i$ is the area projected in the flow direction.

With these definitions, the force balances in the horizontal and vertical
may be expressed as follows.  The top element ($i=1$) has no stress
being applied from above, so the drag and buoyancy are matched with
the stress components, with (Equation 4)
\begin{equation}
\begin{split}
\D_1 &= \T_2 \sin\phi_2\cr
\B_1 &= \T_2 \cos\phi_2
\end{split}
\end{equation}
from which $\phi_2$ and $\T_2$ may be inferred with (Equation 5)
\begin{equation}
\begin{split}
\phi_2 &= \tan^{-1}\frac{\D_1}{\B_1}\cr
\T_2 &= \sqrt{\D_1^2 + \B_1^2}
\end{split}
\end{equation}

The force balance for the second element ($i=2$) is (Equation 6)
\begin{equation}
\begin{split}
\D_2 + \T_2 \sin\phi_2 &= \T_3 \sin\phi_3\cr
\B_2 + \T_2 \cos\phi_2 &= \T_3 \cos\phi_3
\end{split}
\end{equation}
Since $\phi_2$ and $\T_2$ are known from Equation 5, Equation 6 may be solved
with (Equation 7)
\begin{equation}
\begin{split}
\phi_3 &= \tan^{-1}\frac{\D_2+\T_2\sin\phi_2}{\B_2+\T_2\cos\phi_2}\cr
\T_3 &= \sqrt{(\D_2+\T_2\sin\phi_2)^2 + (\B_2+\T_2\cos\phi_2)^2}
\end{split}
\end{equation}

This reasoning applies for all interior elements, so that Equation 7 may be
generalized to (Equation 8)
\begin{equation}
\begin{split}
\phi_i &= \tan^{-1}\frac{\D_{i-1}+\T_{i-1}\sin\phi_{i-1}}{\B_{i-1}+\T_{i-1}\cos\phi_{i-1}}\cr
\T_i &= \sqrt{(\D_{i-1}+\T_{i-1}\sin\phi_{i-1})^2+(\B_{i-1}+\T_{i-1}\cos\phi_{i-1})^2}
\end{split}
\end{equation}
for $i=2,\dots,n$, so that the mooring shape may be inferred by a stepwise
method, working from the top element downwards through the water column:

1. First, use Equation 5 to compute $\phi_2$ and $\T_2$, the angle and tension below
   the top element.
2. Then, use Equation 8 to compute $\phi_i$ and $\T_i$ for $i=3$, then $i=4$, etc.
   until reaching $i=n$.

If the current is depth-variable, the drag values $\D_i$ depend on the local
velocity, and so the mooring shape must be taken into account.  This can be
handled by applying the calculation procedure iteratively, starting with the
assumption of a vertical mooring, and computing vertical positions of
components by taking $\phi_i$ values into account, from the bottom up.

# Example

Figure 1 shows the result of simulating a *Hydro Float 20* float connected to
the bottom with a *Mooring Systems 3x19 3/16"* wire cable, in a region with a
depth-independent 2m/s current, which might be encountered in a region with
strong tides.  Note that the float is predicted to sink $9.33$m with this
current.  However, the predicted knockdown is only $0.72$m with a $1$m/s
current.  This difference provides an indication of the importance of designing
a mooring for the system under study.

```{r echo=FALSE,dev.args=list(pointsize=9),fig.cap="Response of a mooring consisting of a *Hydro Float 20* atop 100m of *Mooring Systems 3x19 3/16\"* wire cable, in a 1m/s current. **Left**: Cable tension, in kg, with gray for the $u=0$ case and black for $u=1$m/s. **Right:** Mooring shape, with gray and black as in the left panel."}
source("example_01.R")
```


# Special case: negligible currents

As a special case, if $u_i=0$ for all $i$, then there will be no drag, and so
(assuming adequate buoyancy), the mooring will be aligned in the vertical, and
the vertical equation becomes
\begin{equation}
\T_{i+1} = \T_i + \B_i
\end{equation}
which yields
\begin{equation}
\T_i = \sum_{1}^{i-1} \B_j
\end{equation}
for $i>1$.  Physically, this means that the downward tension at any level
balances the total upward buoyancy force of all the elements above it. The
bottom tension, $\T_n$, may be interpreted as the minimum anchor weight that
will hold the mooring in place in the absence of currents. However, it should
be obvious that heavier weights will be required for practical situations.

# References


