---
title: Object-orientation Scheme
author: Dan Kelley
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    fig_caption: yes
    fig_width: 3.5
    fig_height: 3.5
    dpi: 72
    dev.args: list(pointsize=11)
vignette: >
  %\VignetteIndexEntry{Object-orientation Scheme}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  markdown:
    wrap: 72
---

The S3 scheme is used for objects created by functions in the `mooring`
package. These objects inherit from the `"mooring"` class.  The contents
consist of a list that in turn contains one or more lists.

The elementary functions, [anchor()], [chain()], [wire()] and [float()],
produce objects with main class `"mooring"` and sub-class with the function
name.  The contents vary from subclass to subclass.  For example, a discrete
object like an anchor or a float has a certain buoyancy, so that is saved in a
field called `buoyancy` that has units of kg (converted from Newtons by
dividing by the acceleration due to gravity).  However, a wire's `buoyancy`
field in units of kg/m, representing buoyancy per length.  Another difference
relates to size.  Following Dewey's convention, a float is stored with a
diameter, whereas a wire or a chain is stored with a width.  Allowances for
these different aspects are made in [knockdown()], as it computes drag and
buoyancy forces on elements.

For example,
```{r}
library(mooring)
m <- mooring(anchor(depth=100), wire(length=75), float())
```
produces a list with 3 elements, one that holds information on the anchor, a
second that holds information on the wire, and a third that holds information
on the float.
