on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board_Overdue:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project-url: "https://github.com/dankelley/mooring/projects/1"
        column-name: "In progress"
        label-name: "In progress"
